# SPDX-License-Identifier: MIT

name: My Checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  vm-amd:
    runs-on: arm-hosted-ubuntu-amd64
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
      - run: aws iot create-thing  --thing-name vm-amd --region eu-west-1
      - run: aws iot delete-thing  --thing-name vm-amd --region eu-west-1
  vm-arm:
    runs-on: arm-hosted-ubuntu-arm64
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
      - run: aws iot create-thing  --thing-name vm-arm --region eu-west-1
      - run: aws iot delete-thing  --thing-name vm-arm --region eu-west-1
  container-test-job-amd64:
    runs-on: arm-hosted-ubuntu-amd64
    container: ubuntu:latest
    steps:
    - name: Clone This Repo
      uses: actions/checkout@v2
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: apt update -y
    - run: apt install curl unzip -y
    - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - run: unzip awscliv2.zip
    - run: ./aws/install
    - run: aws iot create-thing  --thing-name cont-amd --region eu-west-1
    - run: aws iot delete-thing  --thing-name cont-amd --region eu-west-1
    - run: sleep 60
  container-test-job-arm64:
    runs-on: arm-hosted-ubuntu-arm64
    container: ubuntu:latest
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: apt update -y
    - run: apt install curl unzip -y
    - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
    - run: unzip awscliv2.zip
    - run: ./aws/install
    - run: aws iot create-thing  --thing-name cont-arm --region eu-west-1
    - run: aws iot delete-thing  --thing-name cont-arm --region eu-west-1
    - run: sleep 60
