# SPDX-License-Identifier: MIT

name: My Checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  spell-check-amd:
    runs-on: arm-hosted-ubuntu-amd64
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
      - name: Run spellings check
        uses: FreeRTOS/CI-CD-Github-Actions/spellings@main
        with:
          path: ./
  spell-check-arm:
    runs-on: arm-hosted-ubuntu-arm64
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
      - name: Run spellings check
        uses: FreeRTOS/CI-CD-Github-Actions/spellings@main
        with:
          path: ./
  container-test-job-amd64:
    runs-on: arm-hosted-ubuntu-amd64
    container: ubuntu:latest
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: sleep 60
  container-test-job-arm64:
    runs-on: arm-hosted-ubuntu-arm64
    container: ubuntu:latest
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: sleep 60
